### ISSUE TITLE
How to output the path

### ISSUE THREAD

**Issue by zhang181** [JingtianYan/PSB-AAAI#1]
I want to get the path of each agent, what should I do. Thanks.

**Comment by JingtianYan** [comment]
Hi, you can specify the output path via the '--output' option (It is defaulted to "output.txt").

**Comment by zhang181** [comment]
Thanks for your answer, I tried it and it didn't work, I wanted to know the path in the gridmap, the output of the .csv file is via saveResults(). I saw that there is a printPath(Path) function in PBS.cpp, what is the corresponding variable, thanks!

**Comment by worldlyesterday** [comment]
I encounter the same question! Could you please specify the modification you have made? Thx a lot
